#+TITLE: Construct Dwarf Fortress Lazy Newbee Package in ArchLinux
#+DATE: <2019-08-09 Fri 13:36>
#+LAYOUT: post
#+TAGS: DwarfFortress, Linux
#+CATEGORIES: Games

** Included With This Package
   :PROPERTIES:
   :CUSTOM_ID: included-with-this-package
   :END:

DwarfFortress-LNP 也就是我们常说的懒人包，由游戏本体、工具包和图形包组成。在
archlinux 上，我们无法通过 aur 简单地安装懒人包，因此我们需要分别安装懒人包中的
各个部分来达到同样的效果。

#+HTML: <!-- more -->

懒人包主要包括如下部分：
- [[http://www.bay12forums.com/smf/index.php?topic=140808.0][Pidgeot's PyLNP 0.13 Lazy Newb Pack Python interface]]
- Utilities:
  + [[http://www.bay12forums.com/smf/index.php?topic=139553.0][DFHack Linux V0.44.09-r1 (gcc 5.4.0)]]
  + [[http://www.bay12forums.com/smf/index.php?topic=138754.0][TWBT 6.41]]
  + [[https://github.com/Dwarf-Therapist/Dwarf-Therapist][Dwarf Therapist v39.3.1]] (*compiled with qt5.5.1*)
  + [[http://df.zweistein.cz/soundsense/][Soundsense r2016-1]]
  + [[http://www.bay12forums.com/smf/index.php?topic=159567.0][SoundCenSe GTK 1.4.2]] (*Requires Mono, go [[http://www.mono-project.com/download/#download-lin][HERE]] for install instructions*)
  + [[http://www.joelpt.net/quickfort/][qfconvert 2.04]] (*See ./LNP/about/qfconvert.md for usage instructions*)
  + [[http://www.bay12forums.com/smf/index.php?topic=130030.0][DF Announcement Filter 1.01]] (*Requires Java*)
  + [[http://www.bay12forums.com/smf/index.php?topic=155307.0][Legends Browser 1.17.1]] (*Requires Java 8*)
  + [[http://www.bay12forums.com/smf/index.php?topic=146473.0][Armok Vision 0.19.1]]
- Graphics (Now using [[http://www.bay12forums.com/smf/index.php?topic=155882][fricy's Updated tilesets]]!)
  + [16x16] ASCII
  + [16x16] [[https://github.com/DFgraphics/Afro-Graphics][Afro]]
  + [20x20] [[https://github.com/DFgraphics/AutoReiv][AutoReiv]]
  + [18x18] [[https://github.com/DFgraphics/CLA][CLA]]
  + [24x24] [[https://github.com/DFgraphics/GemSet][GemSet]]
  + [16x16] [[https://github.com/DFgraphics/Ironhand][Ironhand]]
  + [12x12] [[https://github.com/DFgraphics/Jolly-Bastion][Jolly Bastion]]
  + [16x16] [[https://github.com/DFgraphics/Mayday][Mayday]]
  + [32x32] [[https://github.com/jecowa/Meph][Meph-lite]]
  + [16x16] [[https://github.com/DFgraphics/Obsidian][Obsidian]]
  + [16x16] [[https://github.com/DFgraphics/Phoebus][Phoebus]]
  + [16x16] [[https://github.com/DFgraphics/Rally-Ho][Rally Ho]]
  + [16x16] [[https://github.com/DFgraphics/Spacefox][Spacefox]]
  + [20x20] [[https://github.com/DFgraphics/Taffer][Taffer]]
  + [16x16] [[https://github.com/DFgraphics/Tergel][Tergel]]
  + [16x16] [[https://github.com/DFgraphics/Wanderlust][Wanderlust]]

** Utilities
   :PROPERTIES:
   :CUSTOM_ID: utilities
   :END:

*** [[http://www.bay12forums.com/smf/index.php?topic=139553.0][DFHack Linux V0.44.09-r1 (gcc 5.4.0)]]
:PROPERTIES:
:CUSTOM_ID: dfhack-linux-v0.44.09-r1-gcc-5.4.0
:END:

DfHack is an attempt to unite the various ways hack tools access DF memory and
allow for easier development of new tools (and of course, make the game more
enjoyable for players).

In archlinux, we can get DfHack by install it with yay:

#+BEGIN_SRC sh
  yay -S dfhack-twbt-bin
#+END_SRC

As we can see, we installed a DfHack version integrated with TWBT. That means we
don't need to install TWBT again. What's more, package =dfhack-twbt-bin= depends
on the package =dwarffortress= in community repository.

But as default, the =PKGBIULD= file of =dfhack-twbt-bin= will download the dfhack
binary compiled with gcc-4.8, which provide an out-of-date version of
remotefortressreader plugin. To avoid this, you can command the PKGBIULD to
download dfhack compiled with gcc-7. To get this magic as below, edit PKGBIULD
with editor:

#+BEGIN_SRC sh
  ...
  # https://github.com/DFHack/dfhack/releases/download/$_pkgver/dfhack-$_pkgver-Linux-64-gcc-4.8.tar.bz2
  https://github.com/DFHack/dfhack/releases/download/$_pkgver/dfhack-$_pkgver-Linux-64-gcc-7.tar.bz2
  ...
  md5sums=('e630ae2fc93c6c7b55552336da2b6c07'
           '3853c6f890d3541f710f2c4833a9e696'
           '6730da5fec400ece9102552e77996fcb'
           '052a58e7f5f1af8be3ddefe9677b8fc6'
           # 'e200a6225dcf285e2eac19c1d1e118ea'
           'bdbe256099ec9ffd90f391f0d069742f'
           '8eac5ae59dad0397090c4f50d50ef841')
  ...
#+END_SRC

Then run =makepkg= to download lacking files.

*** [[http://www.bay12forums.com/smf/index.php?topic=138754.0][TWBT 6.41]]
    :PROPERTIES:
    :CUSTOM_ID: twbt-6.41
    :END:

This plugin improves various aspects the game interface.

Originally I wrote a small plugin because I was tired seeing coffins instead of
zeroes and all that stuff. It has greately evolved since then. Some functions
may not work or have issues in Adventurer Mode. See readme for all details.

1. Main function is to use separate fonts (tilesets) for map tiles and for text.
   Text and map font may also have different sizes. Map tiles can have any size,
   no requirement to have at least 80x25 grid anymore.
2. Multi-level rendering.
3. Allows to override tile numbers for buildings, items and various tile types.
4. =mapshot= command saves image of the entire map in full size.
5. "Multilayered" rendering where floor is visible behind buildings and
   items. (see here for details)
6. Tiles can have parts that will and parts that will not be affected by
   material colour. (see here for details)
7. "Multilayered" rendering for units too. (see here for details)
8. An option to hide stockpiles (background, not items of course) unless in [q],
   [p] and [k] modes. (see here for details)

To make a long story short, TWBT can greately improve the graphics.

*** [[https://github.com/Dwarf-Therapist/Dwarf-Therapist][Dwarf Therapist v39.3.1]] (*compiled with qt5.5.1*)
    :PROPERTIES:
    :CUSTOM_ID: dwarf-therapist-v39.3.1-compiled-with-qt5.5.1
    :END:

Another life-change utility, as it can access memory when df is running, then
you can manage then labor of dwarves with it. (Conflict with auto-labor in
DfHack)

You can install it with =yay -S dwarftherapist-git=. It's a GUI program written
with Qt. Open it after you opened a map in df, then you can see the labor
informations organized in table.

*** [[http://df.zweistein.cz/soundsense/][Soundsense r2016-1]]
    :PROPERTIES:
    :CUSTOM_ID: soundsense-r2016-1
    :END:

Sound package for df that can be installed with =yay -S soundsense=. It provide
sounds by parsing event changes in =~/.dwarffortress/gamelog.txt=.

*** [[http://www.bay12forums.com/smf/index.php?topic=159567.0][SoundCenSe GTK 1.4.2]] (*Requires Mono, go [[http://www.mono-project.com/download/#download-lin][HERE]] for install instructions*)
    :PROPERTIES:
    :CUSTOM_ID: soundcense-gtk-1.4.2-requires-mono-go-here-for-install-instructions
    :END:

Maybe a fork of Soundsense written by c# and GTK2, by I never run successfully.

*** [[http://www.joelpt.net/quickfort/][qfconvert 2.04]] (*See ./LNP/about/qfconvert.md for usage instructions*)
    :PROPERTIES:
    :CUSTOM_ID: qfconvert-2.04-see-.lnpaboutqfconvert.md-for-usage-instructions
    :END:

Quickfort 2 is a utility for Dwarf Fortress that helps you build fortresses from
"blueprint" .CSV, .XLS, and .XLSX files.

*** [[http://www.bay12forums.com/smf/index.php?topic=130030.0][DF Announcement Filter 1.01]] (*Requires Java*)
    :PROPERTIES:
    :CUSTOM_ID: df-announcement-filter-1.01-requires-java
    :END:

This utility gives you a live feed of announcements without having to pause the
game to check the announcement page. It's configurable, allowing you to only see
the announcements you're actually interested in, and you can also have combat
announcements show up in the feed rather than checking the reports screen.

*** [[http://www.bay12forums.com/smf/index.php?topic=155307.0][Legends Browser 1.17.1]] (*Requires Java 8*)
    :PROPERTIES:
    :CUSTOM_ID: legends-browser-1.17.1-requires-java-8
    :END:

Legends Browser is an multi-platform, open source, java-based legends viewer for
dwarf fortress 0.44. You can read about the legends and stories in browser
interactively. You can download the latest release version in [[https://github.com/robertjanetzko/LegendsBrowser/releases][this page]], then
run it with =java -jar legendsbrowser-1.17.1.jar=. Before that, you should export
a xml file in legend mode.

*** [[http://www.bay12forums.com/smf/index.php?topic=146473.0][Armok Vision 0.19.1]]
    :PROPERTIES:
    :CUSTOM_ID: armok-vision-0.19.1
    :END:

A 3d realtime visualizer for Dwarf Fortress rendering with unity, similar with
stonesense, but can run independent with df.

** Graphics
   :PROPERTIES:
   :CUSTOM_ID: graphics
   :END:

I prefer the Spacefox graphics pack. [[https://github.com/cycoe/Spacefox][This is a fork]] with installation script.
