#+TITLE: 路由器配置教程
#+DATE: <2019-04-30 Tue 21:19>
#+LAYOUT: post
#+TAGS: Network
#+CATEGORIES: Network

** 初次使用
   :PROPERTIES:
   :CUSTOM_ID: 初次使用
   :END:

拿到新的路由器之后，首先检查外包装是否有破损、路由器是否有划痕、插头是否有使用痕
迹、插上电源后指示灯是否正常亮起，以此初步判断路由器是否是全新的，在某东平台上买
电子产品要尤其注意。。。

#+HTML: <!-- more -->

好吧扯远了。。。路由器其实可以算作是一台独立的微型计算机，运行着定制的操作系统
（针对路由器我们叫固件）。但路由器又与我们平常见到的电脑不同，因为它没有标准输入
输出设备，也就是键盘鼠标和显示器。那我们要怎么对路由器进行控制呢，其实有很多种方
式，但无论的使用哪种方式，我们都需要首先连接上路由器。

1. 为路由器插上电
2. 连接路由器的方式有两种------有线和无线连接。任选其一即可。

   1. 有线连接：使用网线一头连接路由器的 LAN（Local Area Network）口，一头连接电
      脑的网线口
   2. 无线连接：打开 Wi-Fi 并连接路由器，一般初始名字为 "TP-LINK_XXX"

3. 在浏览器中输入 =192.168.1.1= 打开路由器管理界面（也可能是其他 IP 地址，一般在路
   由器底部的标签上可以看到）
4. 这个时候，根据配置向导对路由器进行配置即可。需要注意的是对于校园网，在 WAN 口
   连接方式中，选择 =动态 IP= 选项。其他的 SSID 名（也就是平常说的 Wi-Fi 名）及
   密码等根据需要进行配置即可

** 高级配置
   :PROPERTIES:
   :CUSTOM_ID: 高级配置
   :END:

在路由器管理页面中，我们可以看到非常多的配置选项。虽然平常在家庭使用中我们只会用
到其中的几个选项，但对于实验室这样一个需要对几十台设备进行管理的场景，里面的一些
选项就会非常有用了。

*** 静态 IP 地址绑定
    :PROPERTIES:
    :CUSTOM_ID: 静态-ip-地址绑定
    :END:

这是我最常用到的一个功能，通俗的讲就是将一个设备的 IP 的地址固定下来。一个设备在
通过路由器连入互联网时，路由器会通过 DHCP（Dynamic Host Configuration Protocol
动态主机设置协议）服务为每个设备随机分配 IP 地址，并且每过一段时间就会改变。那么
我们想在局域网中找到另一台设备就需要通过 IP 地址，而静态 IP 地址绑定就是要告诉路
由器，我想为一台特定设备分配一个固定的 IP 地址，那么我以后就可以通过这个固定的
IP 地址来找到这台设备。

现在的路由器几乎都有这个功能，一般是在 /基本设置-LAN 设置-静态地址分配/ 中进行设置。
其中 =MAC 地址= 是设备的硬件地址，是一串唯一的 12 位的十六进制数，在设备出厂时就确
定好了。可通过我写的小程序获得。 =IP 地址= 是你希望该设备使用的 IP 地址。

*** 路由器桥接
    :PROPERTIES:
    :CUSTOM_ID: 路由器桥接
    :END:
